---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - learn.gocrazy.com
  resources:
  - blockchains
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - learn.gocrazy.com
  resources:
  - blockchains/finalizers
  verbs:
  - update
- apiGroups:
  - learn.gocrazy.com
  resources:
  - blockchains/status
  verbs:
  - get
  - patch
  - update
